Backport/backport 208 to 2.x
opensearch-project/neural-search pull request #210
Opened 2023-07-11 03:27 UTC by zane-neo

### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
    - [ ] All tests pass
- [ ] New functionality has been documented.
    - [ ] New functionality has javadoc added
- [ ] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-07-11 09:38 UTC, navneet1v commented on src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
> +    private static final int MAX_RETRY = 3;
Why this is added?

2023-07-11 14:51 UTC, martin-gaievski approved these changes

2023-07-11 16:50 UTC, martin-gaievski requested changes
I rechecked PRs content, isn't it exactly same as https://github.com/opensearch-project/neural-search/pull/208? https://github.com/opensearch-project/neural-search/pull/208 is also merged to 2.x, so this PR (210) looks like a duplicate. 
@zane-neo can you please check that this PR is actually needed.

2023-07-12 03:30 UTC, navneet1v commented
@zane-neo we should close this PR. The backport has already happened for 2.x branch

2023-07-15 03:02 UTC, closed without merging